Repository inspec/train, pull requests merged in 2018-12, with the labels that each got.

#392 Expose additional winrm options
  lib/train/transports/winrm.rb
  test/unit/transports/winrm_test.rb
Labels: Transport: WinRM, Type: New Feature, Version: Bump Minor

#388 Only ship the runtime files in the gem to slim install sizes
  train-core.gemspec
  train.gemspec
Labels: Aspect: Packaging, Type: Enhancement

#390 Update Travis config for Xenial / Ruby 2.6 and latest patchlevels of Ruby 2.2-2.5
  .travis.yml
  Gemfile
Labels: Aspect: Testing, Type: Enhancement
