Repository inspec/train, pull requests merged in 2019-12, with the labels that each got.

#541 Add azure_mgmt_security to train.gemspec
  train.gemspec
Labels: Expeditor: Bump Minor Version, Platform: Azure, Type: New Feature

#542 Update expeditor config to use colons in labels
  .expeditor/config.yml
Labels: Expeditor: Skip All

#543 Bump minor version
  README.md
Labels: Expeditor: Bump Minor Version
