Repository inspec/train, pull requests merged in 2019-01, with the labels that each got.

#396 drop ruby 2.0-2.2 support, allow bundler 2.x, bump integration gems, allow mixlib-shellout 3.x
  .travis.yml
  Gemfile
  appveyor.yml
  lib/train/transports/gcp.rb
  test/unit/transports/gcp_test.rb
  train.gemspec
Labels: Aspect: Packaging, Aspect: Testing

#389 Remove compat with unsupported Ruby 1.9 in the Gemfile
  Gemfile
Labels: Aspect: Packaging, Type: Enhancement, Version: Bump Minor

#394 Prepare train for using credential sets
  lib/train.rb
  test/unit/helper.rb
  test/unit/train_test.rb
Labels: Aspect: Integration, Type: Enhancement
